apiVersion: v1
data:
  application.properties: "## Common\nspring.jpa.show-sql=true\n\n\n## h2 \n# spring.datasource.url=jdbc:h2:mem:employees\n# spring.datasource.driverClassName=org.h2.Driver\n# spring.datasource.username=sa\n# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect\n# spring.h2.console.enabled=true\n# spring.jpa.hibernate.ddl-auto=none\n\n# mariadb export SPRING_DATASOURCE_URL=jdbc:mariadb://localhost:3306/employees\nspring.datasource.initialization-mode=never\n\nspring.datasource.url=jdbc:mariadb://employeedb.backing-svc:3306/employees\nspring.datasource.username=root\nspring.datasource.password=passw@rd\nspring.datasource.driver-class-name=org.mariadb.jdbc.Driver\n"
kind: ConfigMap
metadata:
  name: config-2cfbb9d644
  namespace: sam
---
apiVersion: v1
kind: Service
metadata:
  name: employees
  namespace: sam
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: tomcat
  selector:
    app: employees
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employees
  name: employees
  namespace: sam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employees
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - image: nogada/employees
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60
        name: employees
        ports:
        - containerPort: 8080
          name: tomcat
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
        volumeMounts:
        - mountPath: /app/config
          name: spring-properties
      volumes:
      - configMap:
          name: config-2cfbb9d644
        name: spring-properties
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: employees
  namespace: sam
spec:
  rules:
  - host: sam.htdp1.kubepia.net
    http:
      paths:
      - backend:
          service:
            name: employees
            port:
              number: http
        path: /
        pathType: Prefix
